config/routes.rb
Rails.application.routes.draw do
  get 'cats/index'
  get 'cats/create'
  get 'cats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    
    validates :sex, inclusion: { in: %w{M F} }

    def age
        # Subtracting the DOB (converted to time) from now; which returns the difference in seconds.
        # Divide the result by the amount of seconds in 1 year, which we can handily get in Rails using 1.year.seconds.
        # Finally floor the result to make sure we always round down
        ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    # render :index
  end

  def create

    # render :create
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    
    # render :show
  end

  private
  def cats_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/index.html.erb
<h1>Cats#index</h1>

<ul>
    <% @cats.each do |cat| %>
        <li>
            <ul>
                <li><%= cat.name %></li>
                <li><%= cat.age %></li>
                <li><%= cat.color %></li>
                <li><%= cat.sex %></li>
                <li><%= link_to "Show Cat Information", cat_url(cat) %></li>
            </ul>
        </li>
        </br>

    <% end %>
</ul>

app/views/cats/show.html.erb
<h1>Cats#show</h1>
<ul>
    <li><%= @cat.name %></li>
    <li><%= @cat.age %></li>
    <li><%= @cat.color %></li>
    <li><%= @cat.sex %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>